<?php
// content/samples.php - Sample gallery filters and data

$samplesFilters = [
    'goals' => ['Quick', 'Family', 'Budget', 'High-Protein', 'Meal-Prep', 'Kid-friendly', 'Weeknight', 'One-pan', 'No-cook'],
    'diet' => ['Vegan', 'Vegetarian', 'Gluten-free', 'Dairy-free', 'Pescatarian', 'Low-carb'],
    'timeOptions' => ['15', '30', '45', 'Any'],
    'skillOptions' => ['Easy', 'Medium', 'Advanced'],
    'cuisines' => ['Italian', 'Asian', 'Mexican', 'Mediterranean', 'Indian', 'Other'],
    'sort' => ['Popular', 'Newest', 'Time'],
];

$samplesData = [
    [
        'id' => 's1',
        'title' => 'Chicken & Broccoli Weeknight Bowl',
        'description' => 'Fast stir-fry with lemon garlic glaze and fluffy rice for busy evenings.',
        'tags' => ['Quick', 'Weeknight', 'High-Protein'],
        'diet' => ['High-Protein', 'Gluten-free'],
        'time' => 20,
        'servings' => 2,
        'skill' => 'Easy',
        'cuisine' => 'Asian',
        'include' => ['chicken breast', 'broccoli', 'garlic', 'lemon', 'rice'],
        'exclude' => ['peanuts'],
        'ingredients' => [
            '250g chicken breast, sliced',
            '1 head broccoli, florets',
            '2 cloves garlic, minced',
            '1 tbsp soy sauce',
            '1 lemon, zest & juice',
            '2 cups cooked jasmine rice',
        ],
        'instructions' => [
            'Toss chicken with soy, lemon, salt and pepper; rest 5 minutes.',
            'Sear chicken in a hot skillet with oil until golden; remove.',
            'Stir-fry broccoli and garlic with a splash of water until crisp-tender.',
            'Return chicken, add lemon juice, toss through and serve over warm rice.',
        ],
        'image' => [
            'src' => 'assets/images/samples/sample-chicken-broccoli-bowl.webp',
            'alt' => 'Chicken and broccoli bowl served over rice with lemon wedges',
        ],
        'popularityScore' => 98,
        'createdAt' => '2025-07-12',
        'generatorPayload' => [
            'include' => ['chicken breast', 'broccoli', 'garlic'],
            'exclude' => ['peanuts'],
            'diet' => ['High-Protein'],
            'time' => 20,
            'skill' => 'Easy',
            'cuisine' => 'Asian',
        ],
    ],
    [
        'id' => 's2',
        'title' => 'Vegan Lentil Tomato One-Pot',
        'description' => 'Comforting lentils simmered with tomatoes, basil and spinach in one pot.',
        'tags' => ['Meal-Prep', 'Budget', 'One-pan'],
        'diet' => ['Vegan'],
        'time' => 30,
        'servings' => 4,
        'skill' => 'Easy',
        'cuisine' => 'Mediterranean',
        'include' => ['red lentils', 'tomatoes', 'spinach'],
        'exclude' => [],
        'ingredients' => [
            '1 cup red lentils, rinsed',
            '1 can crushed tomatoes',
            '3 cups vegetable stock',
            '1 onion, diced',
            '2 cups baby spinach',
            'Fresh basil & olive oil to finish',
        ],
        'instructions' => [
            'Sweat onion and garlic in olive oil until translucent.',
            'Stir in lentils, tomatoes and stock; simmer 20 minutes.',
            'Fold in spinach and basil, cook until wilted.',
            'Season and portion into bowls or containers.',
        ],
        'image' => [
            'src' => 'assets/images/samples/sample-vegan-lentil-onepot.webp',
            'alt' => 'Vegan lentil tomato stew in a pot with basil garnish',
        ],
        'popularityScore' => 92,
        'createdAt' => '2025-06-30',
        'generatorPayload' => [
            'include' => ['red lentils', 'spinach', 'tomatoes'],
            'diet' => ['Vegan'],
            'time' => 30,
            'skill' => 'Easy',
            'cuisine' => 'Mediterranean',
        ],
    ],
    [
        'id' => 's3',
        'title' => 'Garlic Butter Shrimp Pasta',
        'description' => 'Silky linguine coated in garlic butter with juicy shrimp and herbs.',
        'tags' => ['Weeknight', 'Dinner Party'],
        'diet' => ['Pescatarian'],
        'time' => 25,
        'servings' => 3,
        'skill' => 'Medium',
        'cuisine' => 'Italian',
        'include' => ['shrimp', 'linguine', 'garlic', 'butter'],
        'exclude' => ['dairy'],
        'ingredients' => [
            '300g linguine',
            '300g raw shrimp, peeled',
            '60g butter',
            '3 cloves garlic, sliced',
            'Zest of 1 lemon',
            'Fresh parsley to finish',
        ],
        'instructions' => [
            'Cook linguine until al dente; reserve 1/2 cup pasta water.',
            'Sauté garlic in butter until fragrant, add shrimp and cook until pink.',
            'Toss pasta with shrimp, lemon zest and pasta water to create sauce.',
            'Finish with parsley, season and serve immediately.',
        ],
        'image' => [
            'src' => 'assets/images/samples/sample-garlic-butter-shrimp-pasta.webp',
            'alt' => 'Garlic butter shrimp pasta twirled in a bowl',
        ],
        'popularityScore' => 88,
        'createdAt' => '2025-07-08',
        'generatorPayload' => [
            'include' => ['shrimp', 'garlic', 'butter'],
            'exclude' => ['dairy'],
            'diet' => ['Pescatarian'],
            'time' => 25,
            'skill' => 'Medium',
            'cuisine' => 'Italian',
        ],
    ],
    [
        'id' => 's4',
        'title' => 'Mediterranean Chickpea Salad',
        'description' => 'Bright chickpea salad with cucumbers, olives and lemon tahini dressing.',
        'tags' => ['No-cook', 'Meal-Prep'],
        'diet' => ['Vegetarian', 'Gluten-free'],
        'time' => 15,
        'servings' => 3,
        'skill' => 'Easy',
        'cuisine' => 'Mediterranean',
        'include' => ['chickpeas', 'cucumber', 'olive', 'feta'],
        'exclude' => [],
        'ingredients' => [
            '2 cans chickpeas, rinsed',
            '1 cucumber, diced',
            '1 cup cherry tomatoes, halved',
            '1/2 cup Kalamata olives',
            '60g feta, crumbled',
            'Lemon tahini dressing',
        ],
        'instructions' => [
            'Combine chickpeas, cucumber, tomatoes and olives in a bowl.',
            'Whisk together tahini, lemon juice, olive oil and garlic.',
            'Drizzle dressing over salad and toss gently.',
            'Top with feta and herbs before serving.',
        ],
        'image' => [
            'src' => 'assets/images/samples/sample-chickpea-salad.webp',
            'alt' => 'Mediterranean chickpea salad with cucumbers and olives',
        ],
        'popularityScore' => 86,
        'createdAt' => '2025-06-18',
        'generatorPayload' => [
            'include' => ['chickpeas', 'cucumber', 'feta'],
            'diet' => ['Vegetarian'],
            'time' => 15,
            'skill' => 'Easy',
            'cuisine' => 'Mediterranean',
        ],
    ],
    [
        'id' => 's5',
        'title' => 'Spicy Tofu Stir-Fry',
        'description' => 'Crisped tofu tossed in a gochujang sauce with peppers and snap peas.',
        'tags' => ['High-Protein', 'Meal-Prep', 'One-pan'],
        'diet' => ['Vegan'],
        'time' => 18,
        'servings' => 2,
        'skill' => 'Easy',
        'cuisine' => 'Asian',
        'include' => ['tofu', 'gochujang', 'bell pepper'],
        'exclude' => ['peanuts'],
        'ingredients' => [
            '400g firm tofu, cubed',
            '1 tbsp gochujang',
            '1 red bell pepper, sliced',
            '1 cup snap peas',
            '2 cloves garlic, minced',
            'Steamed rice to serve',
        ],
        'instructions' => [
            'Press tofu, toss with cornstarch and sear until crisp.',
            'Sauté garlic, peppers and snap peas briefly.',
            'Stir gochujang with soy, maple syrup and water; add to pan.',
            'Toss tofu in sauce until glossy; serve over rice.',
        ],
        'image' => [
            'src' => 'assets/images/samples/sample-spicy-tofu-stirfry.webp',
            'alt' => 'Spicy tofu stir fry with peppers and sesame seeds',
        ],
        'popularityScore' => 90,
        'createdAt' => '2025-07-02',
        'generatorPayload' => [
            'include' => ['tofu', 'gochujang', 'snap peas'],
            'exclude' => ['peanuts'],
            'diet' => ['Vegan'],
            'time' => 18,
            'skill' => 'Easy',
            'cuisine' => 'Asian',
        ],
    ],
    [
        'id' => 's6',
        'title' => 'Creamy Mushroom Risotto',
        'description' => 'Classic arborio risotto with roasted mushrooms and parmesan.',
        'tags' => ['Comfort Food', 'Date Night'],
        'diet' => ['Vegetarian'],
        'time' => 35,
        'servings' => 3,
        'skill' => 'Medium',
        'cuisine' => 'Italian',
        'include' => ['arborio rice', 'mushrooms', 'parmesan'],
        'exclude' => [],
        'ingredients' => [
            '1 cup arborio rice',
            '250g mixed mushrooms, sliced',
            '1 shallot, minced',
            '1/2 cup white wine',
            '4 cups vegetable stock, warm',
            '40g parmesan, grated',
        ],
        'instructions' => [
            'Sauté mushrooms until golden; reserve.',
            'Sweat shallot in butter, add rice and toast lightly.',
            'Deglaze with wine, then add stock gradually, stirring.',
            'Fold in mushrooms and parmesan to finish.',
        ],
        'image' => [
            'src' => 'assets/images/samples/sample-mushroom-risotto.webp',
            'alt' => 'Creamy mushroom risotto in a bowl with parmesan',
        ],
        'popularityScore' => 84,
        'createdAt' => '2025-05-28',
        'generatorPayload' => [
            'include' => ['mushrooms', 'arborio rice'],
            'diet' => ['Vegetarian'],
            'time' => 35,
            'skill' => 'Medium',
            'cuisine' => 'Italian',
        ],
    ],
    [
        'id' => 's7',
        'title' => 'Herbed Salmon Traybake',
        'description' => 'Sheet-pan salmon with herb butter potatoes and asparagus.',
        'tags' => ['One-pan', 'High-Protein', 'Weeknight'],
        'diet' => ['Pescatarian', 'Gluten-free'],
        'time' => 25,
        'servings' => 2,
        'skill' => 'Easy',
        'cuisine' => 'Other',
        'include' => ['salmon fillet', 'potatoes', 'asparagus'],
        'exclude' => [],
        'ingredients' => [
            '2 salmon fillets',
            '200g baby potatoes, halved',
            '1 bunch asparagus, trimmed',
            '40g herb butter',
            'Lemon wedges to serve',
        ],
        'instructions' => [
            'Roast potatoes with olive oil and salt for 10 minutes.',
            'Add asparagus and top salmon with herb butter; return to oven.',
            'Bake until salmon flakes easily and potatoes are tender.',
            'Finish with lemon juice and herbs.',
        ],
        'image' => [
            'src' => 'assets/images/samples/sample-herbed-salmon-traybake.webp',
            'alt' => 'Traybake salmon with potatoes and asparagus',
        ],
        'popularityScore' => 91,
        'createdAt' => '2025-07-05',
        'generatorPayload' => [
            'include' => ['salmon', 'potatoes', 'asparagus'],
            'diet' => ['Pescatarian'],
            'time' => 25,
            'skill' => 'Easy',
            'cuisine' => 'Other',
        ],
    ],
    [
        'id' => 's8',
        'title' => 'Kid-Friendly Turkey Meatballs',
        'description' => 'Baked turkey meatballs with hidden veggies and tomato sauce.',
        'tags' => ['Family', 'Kid-friendly', 'Meal-Prep'],
        'diet' => ['High-Protein'],
        'time' => 28,
        'servings' => 4,
        'skill' => 'Easy',
        'cuisine' => 'Italian',
        'include' => ['ground turkey', 'zucchini', 'tomato sauce'],
        'exclude' => [],
        'ingredients' => [
            '500g ground turkey',
            '1 small zucchini, grated',
            '1 egg, beaten',
            '1/2 cup breadcrumbs',
            '2 cups marinara sauce',
            'Fresh basil to serve',
        ],
        'instructions' => [
            'Combine turkey, zucchini, egg, breadcrumbs and seasoning.',
            'Roll into meatballs and bake until cooked through.',
            'Warm marinara in a skillet and nest meatballs inside.',
            'Finish with basil and serve with pasta or veggies.',
        ],
        'image' => [
            'src' => 'assets/images/samples/sample-turkey-meatballs.webp',
            'alt' => 'Turkey meatballs in marinara sauce with basil',
        ],
        'popularityScore' => 87,
        'createdAt' => '2025-06-05',
        'generatorPayload' => [
            'include' => ['ground turkey', 'zucchini'],
            'diet' => ['High-Protein'],
            'time' => 28,
            'skill' => 'Easy',
            'cuisine' => 'Italian',
        ],
    ],
    [
        'id' => 's9',
        'title' => 'High-Protein Quinoa Power Bowl',
        'description' => 'Quinoa base with roasted chickpeas, avocado and lemon yogurt.',
        'tags' => ['Meal-Prep', 'High-Protein', 'Budget'],
        'diet' => ['Vegetarian'],
        'time' => 25,
        'servings' => 3,
        'skill' => 'Easy',
        'cuisine' => 'Other',
        'include' => ['quinoa', 'chickpeas', 'avocado'],
        'exclude' => [],
        'ingredients' => [
            '1 cup quinoa, rinsed',
            '1 can chickpeas, drained',
            '1 avocado, sliced',
            '1 cup roasted vegetables',
            'Lemon yogurt sauce',
        ],
        'instructions' => [
            'Cook quinoa and fluff with fork.',
            'Roast chickpeas with paprika until crisp.',
            'Assemble bowls with quinoa, veggies, chickpeas and avocado.',
            'Drizzle with lemon yogurt sauce to finish.',
        ],
        'image' => [
            'src' => 'assets/images/samples/sample-quinoa-power-bowl.webp',
            'alt' => 'Quinoa bowl with chickpeas, avocado and greens',
        ],
        'popularityScore' => 82,
        'createdAt' => '2025-05-22',
        'generatorPayload' => [
            'include' => ['quinoa', 'chickpeas', 'avocado'],
            'diet' => ['Vegetarian'],
            'time' => 25,
            'skill' => 'Easy',
            'cuisine' => 'Other',
        ],
    ],
    [
        'id' => 's10',
        'title' => '15-min Egg Fried Rice',
        'description' => 'Weeknight fried rice with eggs, peas and sesame oil in minutes.',
        'tags' => ['Quick', 'Budget', 'Weeknight'],
        'diet' => ['Vegetarian'],
        'time' => 15,
        'servings' => 2,
        'skill' => 'Easy',
        'cuisine' => 'Asian',
        'include' => ['rice', 'eggs', 'peas', 'sesame oil'],
        'exclude' => ['nuts'],
        'ingredients' => [
            '2 cups day-old rice',
            '2 eggs, beaten',
            '1 cup frozen peas & carrots',
            '2 green onions, sliced',
            '1 tbsp sesame oil',
            'Soy sauce to taste',
        ],
        'instructions' => [
            'Scramble eggs in a wok; remove and reserve.',
            'Stir-fry rice with sesame oil until hot.',
            'Add vegetables, soy sauce, and return eggs.',
            'Finish with green onions and serve.',
        ],
        'image' => [
            'src' => 'assets/images/samples/sample-egg-fried-rice.webp',
            'alt' => 'Egg fried rice in a bowl with green onions',
        ],
        'popularityScore' => 95,
        'createdAt' => '2025-07-10',
        'generatorPayload' => [
            'include' => ['rice', 'eggs', 'peas'],
            'exclude' => ['nuts'],
            'diet' => ['Vegetarian'],
            'time' => 15,
            'skill' => 'Easy',
            'cuisine' => 'Asian',
        ],
    ],
    [
        'id' => 's11',
        'title' => 'Mexican Bean & Corn Tacos',
        'description' => 'Weeknight tacos loaded with beans, charred corn and fresh salsa.',
        'tags' => ['Family', 'Budget', 'Weeknight'],
        'diet' => ['Vegetarian'],
        'time' => 22,
        'servings' => 4,
        'skill' => 'Easy',
        'cuisine' => 'Mexican',
        'include' => ['black beans', 'corn', 'tortillas'],
        'exclude' => [],
        'ingredients' => [
            '1 can black beans, rinsed',
            '1 cup charred corn kernels',
            '8 small tortillas',
            '1 red onion, sliced',
            'Fresh salsa and cilantro',
        ],
        'instructions' => [
            'Warm beans with spices in a skillet.',
            'Char corn and onion until smoky.',
            'Warm tortillas and fill with beans, corn and salsa.',
            'Top with cilantro and serve immediately.',
        ],
        'image' => [
            'src' => 'assets/images/samples/sample-bean-corn-tacos.webp',
            'alt' => 'Bean and corn tacos with lime wedges',
        ],
        'popularityScore' => 89,
        'createdAt' => '2025-06-12',
        'generatorPayload' => [
            'include' => ['black beans', 'corn'],
            'diet' => ['Vegetarian'],
            'time' => 22,
            'skill' => 'Easy',
            'cuisine' => 'Mexican',
        ],
    ],
    [
        'id' => 's12',
        'title' => 'Pesto Chicken Orzo',
        'description' => 'Creamy pesto orzo with seared chicken, tomatoes and spinach.',
        'tags' => ['Weeknight', 'Family'],
        'diet' => ['High-Protein'],
        'time' => 24,
        'servings' => 3,
        'skill' => 'Easy',
        'cuisine' => 'Italian',
        'include' => ['chicken', 'orzo', 'pesto'],
        'exclude' => [],
        'ingredients' => [
            '300g chicken thigh, sliced',
            '1 cup orzo pasta',
            '3 tbsp basil pesto',
            '1 cup baby spinach',
            '1/2 cup cherry tomatoes',
            '30g parmesan, grated',
        ],
        'instructions' => [
            'Sear chicken until golden; set aside.',
            'Cook orzo in stock until al dente.',
            'Stir in pesto, spinach and tomatoes.',
            'Fold chicken back in, finish with parmesan.',
        ],
        'image' => [
            'src' => 'assets/images/samples/sample-pesto-chicken-orzo.webp',
            'alt' => 'Pesto chicken orzo with spinach and tomatoes',
        ],
        'popularityScore' => 93,
        'createdAt' => '2025-07-01',
        'generatorPayload' => [
            'include' => ['chicken', 'orzo', 'pesto'],
            'diet' => ['High-Protein'],
            'time' => 24,
            'skill' => 'Easy',
            'cuisine' => 'Italian',
        ],
    ],
];
